name: vuepress-deploy
on: 
  push:
    branches:
      - master
env:
  TZ: Asia/Shanghai
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 15.x
      - name: build and deploy
        env:
          NAME: ${{ secrets.ACCESS_NAME }}
          EMAIL: ${{ secrets.ACCESS_EMAIL }}
          ORIGIN: ${{ secrets.ACCESS_ORIGIN }}
        run: |
          yarn config set registry https://r.npm.taobao.org
          yarn
          yarn build
          cd src/.vuepress/dist
          git init
          git config user.name "$NAME"
          git config user.email "$EMAIL"
          git add -A
          git commit -q -m "Auto Deploy from Github Actions: $(date +"%Y-%m-%d %H:%M")"
          git push -f "$ORIGIN" master:gh-pages
